Create lsm6ds3.py
adafruit/Adafruit_CircuitPython_LSM6DS pull request #56
Opened 2022-04-06 10:42 UTC by Edrig

add support to lsm6ds3 IMU
(IMU in board Xiao BLE SENSE)

2022-04-06 14:46 UTC, FoamyGuy commented
Thanks for this addition Edrig. The CI checks failed due to the code needing to be formatted with the Black code formatter. There is a guide page here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code that shows how you can use pre-commit to run all of the same checks that the CI actions are doing. 

The next few pages in the guide after this one show the individual componenets that make up the checks which you can also run individually without pre-commit but it's much more convenient to run them all at once as shown on this page.

2022-04-06 16:25 UTC, Edrig commented
@FoamyGuy All checks have passed ^^
Thank you for the tips pre-commit check

2022-04-11 21:26 UTC, FoamyGuy requested changes
Looks pretty good to me, but I have a few suggested changes. 

Thanks for adding support for this different variant of hardware @Edrig

2022-04-11 21:26 UTC, FoamyGuy commented on adafruit_lsm6ds/lsm6ds3.py
> +# SPDX-FileCopyrightText: Copyright (c) 2020 Bryan Siepert for Adafruit Industries
You can put your own name, and the current year for this copyright comment in the new file.

2022-04-11 21:26 UTC, FoamyGuy commented on examples/lsm6ds_lsm6ds3_simpletest.py
> +# SPDX-FileCopyrightText: Copyright (c) 2020 Bryan Siepert for Adafruit Industries
same thing here, you can use your own name and this year.

2022-05-02 15:09 UTC, FoamyGuy approved these changes
I added one commit to change the copyrights to your username and changed a few instances of `LSM6DS33` to `LSM6DS3` in the docstrings.

This is looking good to me after those changes. Don't have the specific hardware to test but changes make sense for the new class that supports hardware with address `0x6A`

2022-05-02 15:09 UTC, merged